package ifneeded lcd 1.0 [list source [file join $dir lcd.tcl]]
package ifneeded task 1.0 [list source [file join $dir task.tcl]]
package ifneeded date 1.0 [list source [file join $dir date.tcl]]
package ifneeded host 1.0 [list source [file join $dir host.tcl]]
package ifneeded uptime 1.0 [list source [file join $dir uptime.tcl]]
package ifneeded gpsd 1.0 [list source [file join $dir gpsd.tcl]]
package ifneeded gps 1.0 [list source [file join $dir gps.tcl]]
